# Configuration de la classe Personne
name: Salarié
icon: 😀
extend: Personne

# Configuration des propriétés
properties:
    
  dateEntree:
    type: DateProperty
    title: Date d'entrée
    icon: 📅
    required: false
    defaultValue: ""
    
  competences:
    type: MultiSelectProperty
    title: Compétences
    icon: 🎯
    required: false
    defaultValue: []
    options:
      - "Management" : ["management"]
      - "Technique"
      - "Communication"
      - "Vente"
      - "Marketing"
      - "Finance"
      - "RH"
      - "Juridique"

    
  notes:
    type: TextProperty
    title: Notes
    icon: 📋
    required: false
    defaultValue: ""
    multiline: true

# Configuration d'affichage
display:
  items:
    - type: line
      title: "Identité"
      className: "personne-identity-section"
      items:
        - type: property
          name: classe
        - type: property
          name: nom
          title: Nom de famille
        - type: property
          name: prenom
        - type: property
          name: institution
    
    - type: tabs
      title: "Informations"
      className: "personne-info-tabs"
      tabs:
        - name: "Professionnel"
          items:
            - type: property
              name: postes
            - type: property
              name: dateEntree
            - type: property
              name: statut
            - type: property
              name: competences
        - name: "Contact"
          items:
            - type: property
              name: email
            - type: property
              name: telephone
    
    - type: fold
      title: "Notes supplémentaires"
      className: "personne-notes-fold"
      items:
        - type: property
          name: notes
